// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsWD_Ieci627CxNa52C5uMCJr7NKQIF8E',
    appId: '1:463241467026:web:9b106a5a7949584a0a024b',
    messagingSenderId: '463241467026',
    projectId: 'pollspace-d2025',
    authDomain: 'pollspace-d2025.firebaseapp.com',
    storageBucket: 'pollspace-d2025.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjYqCJ642o6XWYU0Q1svAYARHAgNo0Euo',
    appId: '1:463241467026:android:fce9fd41ec34c0c90a024b',
    messagingSenderId: '463241467026',
    projectId: 'pollspace-d2025',
    storageBucket: 'pollspace-d2025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjtn-6aG-nC4TkSKf4_kMUqfePF0N4byk',
    appId: '1:463241467026:ios:8821d63fe3930d250a024b',
    messagingSenderId: '463241467026',
    projectId: 'pollspace-d2025',
    storageBucket: 'pollspace-d2025.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjtn-6aG-nC4TkSKf4_kMUqfePF0N4byk',
    appId: '1:463241467026:ios:8821d63fe3930d250a024b',
    messagingSenderId: '463241467026',
    projectId: 'pollspace-d2025',
    storageBucket: 'pollspace-d2025.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsWD_Ieci627CxNa52C5uMCJr7NKQIF8E',
    appId: '1:463241467026:web:90f945568647dee40a024b',
    messagingSenderId: '463241467026',
    projectId: 'pollspace-d2025',
    authDomain: 'pollspace-d2025.firebaseapp.com',
    storageBucket: 'pollspace-d2025.appspot.com',
  );

}